In [124]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

In [125]:
dataset = pd.read_csv("car_price.csv")

In [126]:
dataset.drop(['Unnamed: 0'],axis=1,inplace=True)

In [127]:
dataset.shape

(5512, 9)

In [128]:
dataset.sample(10)

,car_name,car_prices_in_rupee,kms_driven,fuel_type,transmission,ownership,manufacture,engine,Seats
4743,Hyundai i10 Sportz,2.17 Lakh,"55,961 kms",Petrol,Manual,3rd Owner,2011,1997 cc,5 Seats
3889,Maruti Ignis Sigma,4.69 Lakh,"12,000 kms",Petrol,Manual,1st Owner,2021,1197 cc,5 Seats
3726,Honda Amaze S Diesel,4 Lakh,"17,804 kms",Diesel,Manual,1st Owner,2014,1497 cc,5 Seats
3819,Hyundai Santro Xing GL,"85,000","80,000 kms",Petrol,Manual,1st Owner,2008,1197 cc,5 Seats
3631,Maruti Zen LXI,"65,000","1,00,000 kms",Petrol,Manual,3rd Owner,2004,1194 cc,5 Seats
5257,Hyundai Venue SX Opt iMT,11.50 Lakh,"10,000 kms",Petrol,Manual,1st Owner,2021,1998 cc,5 Seats
2547,Hyundai Verna CRDi 1.6 EX,7.23 Lakh,"24,494 kms",Diesel,Manual,1st Owner,2018,1197 cc,7 Seats
3133,Toyota Land Cruiser VX,1.69 Crore,"27,000 kms",Diesel,Automatic,1st Owner,2019,1199 cc,4 Seats
3720,Renault KWID 1.0 RXT Optional AT 2016-2019,3.40 Lakh,"4,956 kms",Petrol,Automatic,1st Owner,2018,1199 cc,5 Seats
5259,Tata Harrier XM,12.50 Lakh,"32,500 kms",Diesel,Manual,1st Owner,2019,1968 cc,5 Seats

In [129]:
dataset.isnull().sum()

car_name               0
car_prices_in_rupee    0
kms_driven             0
fuel_type              0
transmission           0
ownership              0
manufacture            0
engine                 0
Seats                  0
dtype: int64

In [130]:
dataset['car_name'].value_counts()

car_name
Maruti Alto 800 LXI                     53
Maruti Swift VXI                        46
Maruti Wagon R VXI BS IV                43
Maruti Swift Dzire VDI                  42
Maruti Swift Dzire VXI                  42
                                        ..
Tata Indica Aqua 1.3 Quadrajet (ABS)     1
Mercedes-Benz S-Class S 350 L            1
BMW 7 Series 730Ld Eminence              1
Mahindra XUV300 W6                       1
Honda WR-V VX Diesel                     1
Name: count, Length: 1896, dtype: int64

In [131]:
le = LabelEncoder()

In [132]:
dataset['car_name'] = le.fit_transform(dataset['car_name'])

In [133]:
def convert_lakh(value):
    if isinstance(value, str):
        value = value.lower().replace(',', '').strip()
        if 'lakh' in value:
            return float(value.replace('lakh', '')) * 100000
        elif 'crore' in value:
            return float(value.replace('crore', '')) * 10000000
    return float(value)

dataset['car_prices_in_rupee'] = dataset['car_prices_in_rupee'].apply(convert_lakh)

In [134]:
dataset

,car_name,car_prices_in_rupee,kms_driven,fuel_type,transmission,ownership,manufacture,engine,Seats
0,743,1003000.0,"86,226 kms",Diesel,Manual,1st Owner,2017,1956 cc,5 Seats
1,1444,1283000.0,"13,248 kms",Petrol,Automatic,1st Owner,2021,1330 cc,5 Seats
2,1706,1640000.0,"60,343 kms",Petrol,Automatic,1st Owner,2016,2494 cc,5 Seats
3,385,777000.0,"26,696 kms",Petrol,Automatic,1st Owner,2018,1199 cc,5 Seats
4,1831,515000.0,"69,414 kms",Petrol,Manual,1st Owner,2016,1199 cc,5 Seats
...,...,...,...,...,...,...,...,...,...
5507,82,2890000.0,"45,000 kms",Diesel,Automatic,1st Owner,2018,2995 cc,7 Seats
5508,79,6490000.0,"29,000 kms",Petrol,Automatic,2nd Owner,2015,1968 cc,5 Seats
5509,720,1375000.0,"90,000 kms",Diesel,Automatic,2nd Owner,2013,2755 cc,5 Seats
5510,74,2990000.0,"79,000 kms",Diesel,Automatic,3rd Owner,2015,2967 cc,6 Seats
5511,62,3190000.0,"42,000 kms",Diesel,Automatic,2nd Owner,2017,1991 cc,5 Seats

In [135]:
dataset['car_prices_in_rupee'] = dataset['car_prices_in_rupee'].astype(int)

In [136]:
dataset['car_prices_in_rupee'].dtype

dtype('int64')

In [137]:
dataset

,car_name,car_prices_in_rupee,kms_driven,fuel_type,transmission,ownership,manufacture,engine,Seats
0,743,1002999,"86,226 kms",Diesel,Manual,1st Owner,2017,1956 cc,5 Seats
1,1444,1283000,"13,248 kms",Petrol,Automatic,1st Owner,2021,1330 cc,5 Seats
2,1706,1639999,"60,343 kms",Petrol,Automatic,1st Owner,2016,2494 cc,5 Seats
3,385,777000,"26,696 kms",Petrol,Automatic,1st Owner,2018,1199 cc,5 Seats
4,1831,515000,"69,414 kms",Petrol,Manual,1st Owner,2016,1199 cc,5 Seats
...,...,...,...,...,...,...,...,...,...
5507,82,2890000,"45,000 kms",Diesel,Automatic,1st Owner,2018,2995 cc,7 Seats
5508,79,6490000,"29,000 kms",Petrol,Automatic,2nd Owner,2015,1968 cc,5 Seats
5509,720,1375000,"90,000 kms",Diesel,Automatic,2nd Owner,2013,2755 cc,5 Seats
5510,74,2990000,"79,000 kms",Diesel,Automatic,3rd Owner,2015,2967 cc,6 Seats
5511,62,3190000,"42,000 kms",Diesel,Automatic,2nd Owner,2017,1991 cc,5 Seats

In [138]:
dataset['kms_driven'] = (dataset['kms_driven'].astype(str).str.replace(',', '').str.extract(r'(\d+)').astype(float))

In [139]:
dataset['kms_driven'] = dataset['kms_driven'].astype(int)

In [140]:
dataset['kms_driven']

0       86226
1       13248
2       60343
3       26696
4       69414
        ...
5507    45000
5508    29000
5509    90000
5510    79000
5511    42000
Name: kms_driven, Length: 5512, dtype: int64

In [141]:
dataset.head()

,car_name,car_prices_in_rupee,kms_driven,fuel_type,transmission,ownership,manufacture,engine,Seats
0,743,1002999,86226,Diesel,Manual,1st Owner,2017,1956 cc,5 Seats
1,1444,1283000,13248,Petrol,Automatic,1st Owner,2021,1330 cc,5 Seats
2,1706,1639999,60343,Petrol,Automatic,1st Owner,2016,2494 cc,5 Seats
3,385,777000,26696,Petrol,Automatic,1st Owner,2018,1199 cc,5 Seats
4,1831,515000,69414,Petrol,Manual,1st Owner,2016,1199 cc,5 Seats

In [142]:
dataset['Seats'] = (
    dataset['Seats']
    .astype(str)
    .str.extract(r'(\d+)')
    .astype(int)
)

In [143]:
dataset

,car_name,car_prices_in_rupee,kms_driven,fuel_type,transmission,ownership,manufacture,engine,Seats
0,743,1002999,86226,Diesel,Manual,1st Owner,2017,1956 cc,5
1,1444,1283000,13248,Petrol,Automatic,1st Owner,2021,1330 cc,5
2,1706,1639999,60343,Petrol,Automatic,1st Owner,2016,2494 cc,5
3,385,777000,26696,Petrol,Automatic,1st Owner,2018,1199 cc,5
4,1831,515000,69414,Petrol,Manual,1st Owner,2016,1199 cc,5
...,...,...,...,...,...,...,...,...,...
5507,82,2890000,45000,Diesel,Automatic,1st Owner,2018,2995 cc,7
5508,79,6490000,29000,Petrol,Automatic,2nd Owner,2015,1968 cc,5
5509,720,1375000,90000,Diesel,Automatic,2nd Owner,2013,2755 cc,5
5510,74,2990000,79000,Diesel,Automatic,3rd Owner,2015,2967 cc,6
5511,62,3190000,42000,Diesel,Automatic,2nd Owner,2017,1991 cc,5

In [144]:
dataset['manufacture'].dtype

dtype('int64')

In [145]:
one = OneHotEncoder(sparse_output=False,drop='first')

In [146]:
encoded = one.fit_transform(dataset[['fuel_type','transmission','ownership']])

In [147]:
encoded_df = pd.DataFrame(
    encoded,
    columns=one.get_feature_names_out(
        ['fuel_type', 'transmission', 'ownership']
    )
)

In [148]:
dataset = dataset.drop(
    ['fuel_type', 'transmission', 'ownership'],
    axis=1
)

dataset = pd.concat([dataset, encoded_df], axis=1)

In [149]:
dataset

,car_name,car_prices_in_rupee,kms_driven,manufacture,engine,Seats,fuel_type_Diesel,fuel_type_Electric,fuel_type_Lpg,fuel_type_Petrol,transmission_Manual,ownership_1st Owner,ownership_2nd Owner,ownership_3rd Owner,ownership_4th Owner,ownership_5th Owner
0,743,1002999,86226,2017,1956 cc,5,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
1,1444,1283000,13248,2021,1330 cc,5,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
2,1706,1639999,60343,2016,2494 cc,5,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
3,385,777000,26696,2018,1199 cc,5,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
4,1831,515000,69414,2016,1199 cc,5,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5507,82,2890000,45000,2018,2995 cc,7,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
5508,79,6490000,29000,2015,1968 cc,5,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
5509,720,1375000,90000,2013,2755 cc,5,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
5510,74,2990000,79000,2015,2967 cc,6,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
5511,62,3190000,42000,2017,1991 cc,5,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [150]:
dataset['engine'] = pd.to_numeric(
    dataset['engine']
    .astype(str)
    .str.replace(',', '', regex=True)
    .str.extract(r'(\d+)')[0],
    errors='coerce'
)

In [152]:
dataset['engine'].dtype

dtype('int64')

In [153]:
dataset

,car_name,car_prices_in_rupee,kms_driven,manufacture,engine,Seats,fuel_type_Diesel,fuel_type_Electric,fuel_type_Lpg,fuel_type_Petrol,transmission_Manual,ownership_1st Owner,ownership_2nd Owner,ownership_3rd Owner,ownership_4th Owner,ownership_5th Owner
0,743,1002999,86226,2017,1956,5,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
1,1444,1283000,13248,2021,1330,5,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
2,1706,1639999,60343,2016,2494,5,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
3,385,777000,26696,2018,1199,5,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
4,1831,515000,69414,2016,1199,5,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5507,82,2890000,45000,2018,2995,7,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
5508,79,6490000,29000,2015,1968,5,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
5509,720,1375000,90000,2013,2755,5,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
5510,74,2990000,79000,2015,2967,6,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
5511,62,3190000,42000,2017,1991,5,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [155]:
x = dataset.drop('car_prices_in_rupee',axis=1)

In [157]:
y = dataset['car_prices_in_rupee']

In [160]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [230]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=87)

In [231]:
standard = StandardScaler()

In [232]:
x_train[["kms_driven","manufacture","engine"]] = standard.fit_transform(x_train[["kms_driven","manufacture","engine"]])

In [233]:
x_test[["kms_driven","manufacture","engine"]] = standard.transform(x_test[["kms_driven","manufacture","engine"]])

In [234]:
from sklearn.tree import DecisionTreeRegressor

In [235]:
from sklearn.metrics import r2_score

In [236]:
dc = DecisionTreeRegressor()

In [237]:
dc.fit(x_train,y_train)

DecisionTreeRegressor()

In [238]:
y_pred = dc.predict(x_test)

In [239]:
dc.score(x_train,y_train)*100

99.99999854824384

In [241]:
r2_score(y_test,y_pred)*100

92.45381497639531

In [229]:
for i in range(1,100):
    x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=i)
    dc1 = DecisionTreeRegressor()
    dc1.fit(x_train,y_train)
    y_pred = dc1.predict(x_test)
    print(dc1.score(x_train,y_train)*100,r2_score(y_test,y_pred)*100,i)

99.99999866147547 82.01187292073149 1
99.99999853822553 71.1512543336913 2
100.0 82.73631254154566 3
99.99999856277577 79.80332648874058 4
100.0 84.96268183871886 5
99.99999857236841 75.91044206997438 6
99.99999860636157 75.95419487842533 7
99.99999847691001 79.50007436014187 8
99.9999985631505 74.30191416484477 9
99.99999855739536 79.54380855757698 10
100.0 69.80727603436964 11
100.0 76.2708116826041 12
99.99999845486894 77.24131334202899 13
99.99999856710274 77.35698335809091 14
99.99999860490726 67.53630898591405 15
99.999998611071 64.85494864588044 16
99.99999861500864 85.54599227906706 17
100.0 76.19881694998858 18
99.99999858426813 71.77830920392748 19
99.9999984801864 85.7830129442604 20
100.0 59.83897532328042 21
99.99999852865146 74.12347691868098 22
100.0 86.09002445572557 23
99.99999857417833 82.08829063550654 24
100.0 85.00253211877234 25
100.0 81.46960646834411 26
99.99999864180295 87.78180874126859 27
99.99999857503849 85.27134287759857 28
99.99999866127331 81.08727303457212 29
99.9999986414215 67.8018943964089 30
99.99999858071249 83.06371346710431 31
100.0 57.83193913043978 32
99.99999863637647 78.562354068542 33
99.99999865243286 63.20355505994111 34
99.9999985564908 77.70642244152374 35
99.99999861615072 75.3085255004464 36
99.99999857439865 81.78100700342374 37
99.9999985877343 66.2081262221554 38
99.99999862954326 66.7425656576184 39
99.99999851264569 81.24551201498006 40
100.0 77.43832055672837 41
99.99999857169715 73.79553813585757 42
99.99999861049879 63.9892716659901 43
99.99999859576548 84.48629228437586 44
99.99999860009727 72.1547988717187 45
99.99999856486012 81.09338867731171 46
99.99999861751138 78.41628710210634 47
99.9999985644096 78.64086831858168 48
99.99999852380081 79.95974739410848 49
100.0 74.62068921265724 50
99.99999853805683 80.95136812395569 51
99.9999986033937 82.56786115211192 52
99.99999859825934 88.1967724986234 53
100.0 67.50230548354833 54
99.99999845355217 75.4265443668725 55
99.99999856432956 64.88312428417295 56
99.99999858611329 83.83181459431987 57
99.99999859781927 86.00478094302824 58
100.0 90.23590337560385 59
99.99999857967407 85.52973707327038 60
100.0 61.52534407486829 61
100.0 82.5988555506751 62
99.99999858603631 92.77337765327806 63
99.99999853433867 67.87368136638274 64
99.99999858465216 80.2337075882325 65
99.99999856495893 83.51553177937151 66
99.99999851079629 70.33562849622896 67
100.0 68.008213860021 68
100.0 81.51086350927024 69
99.99999860496882 88.15583017314277 70
99.99999858884173 86.17549405311094 71
99.99999861392473 91.28324420501541 72
99.9999985646337 82.14620539956489 73
99.99999862686546 82.11766049954979 74
99.99999856101826 83.69548865001106 75
99.99999858136583 86.7809196294265 76
99.9999986459904 79.29727163159006 77
99.99999861885517 66.58216321175587 78
99.99999859469088 70.78469059943761 79
99.99999844170236 73.68677893257826 80
99.9999985103277 84.37113596554859 81
100.0 80.40099875508501 82
100.0 79.16965780329978 83
100.0 85.67066119292284 84
99.9999985669514 77.66620062712153 85
99.99999863926071 73.93285760479647 86
99.99999854824384 92.08409220299434 87
100.0 90.26489337815289 88
99.99999865266734 78.96009192632678 89
99.99999848611083 86.0062088133594 90
100.0 89.28442806621754 91
99.99999861335775 80.43681393380066 92
99.99999856663644 81.25289144266614 93
99.99999850893619 89.77505833685765 94
100.0 83.48457714891575 95
99.99999864811278 81.16634101078878 96
100.0 78.58167207251348 97
99.99999859871112 69.86786018054192 98
99.99999849281942 78.77247377186708 99